"""Schema definitions for tap-branch streams."""

from __future__ import annotations

from singer_sdk import typing as th

# ---------------------------------------------------------------------------
# Shared property groups
# ---------------------------------------------------------------------------

# last_attributed_touch_data tilde fields present in ALL 7 streams
_TOUCH_TILDE: list[th.Property] = [
    th.Property("last_attributed_touch_data_tilde_ad_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_advertising_partner_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_advertising_partner_name", th.StringType),
    th.Property("last_attributed_touch_data_tilde_agency", th.StringType),
    th.Property("last_attributed_touch_data_tilde_agency_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_banner_dimensions", th.StringType),
    th.Property("last_attributed_touch_data_tilde_branch_ad_format", th.StringType),
    th.Property("last_attributed_touch_data_tilde_campaign", th.StringType),
    th.Property("last_attributed_touch_data_tilde_campaign_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_campaign_type", th.StringType),
    th.Property("last_attributed_touch_data_tilde_channel", th.StringType),
    th.Property("last_attributed_touch_data_tilde_creative_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_creative_name", th.StringType),
    th.Property("last_attributed_touch_data_tilde_customer_ad_name", th.StringType),
    th.Property("last_attributed_touch_data_tilde_customer_ad_set_name", th.StringType),
    th.Property("last_attributed_touch_data_tilde_customer_campaign", th.StringType),
    th.Property("last_attributed_touch_data_tilde_customer_keyword", th.StringType),
    th.Property("last_attributed_touch_data_tilde_customer_placement", th.StringType),
    th.Property("last_attributed_touch_data_tilde_customer_secondary_publisher", th.StringType),
    th.Property("last_attributed_touch_data_tilde_customer_sub_site_name", th.StringType),
    th.Property("last_attributed_touch_data_tilde_external_touch_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_feature", th.StringType),
    th.Property("last_attributed_touch_data_tilde_keyword", th.StringType),
    th.Property("last_attributed_touch_data_tilde_keyword_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_optimization_model", th.StringType),
    th.Property("last_attributed_touch_data_tilde_placement", th.StringType),
    th.Property("last_attributed_touch_data_tilde_placement_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_secondary_ad_format", th.StringType),
    th.Property("last_attributed_touch_data_tilde_secondary_publisher", th.StringType),
    th.Property("last_attributed_touch_data_tilde_secondary_publisher_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_stage", th.StringType),
    th.Property("last_attributed_touch_data_tilde_sub_site_name", th.StringType),
    th.Property("last_attributed_touch_data_tilde_tags", th.StringType),
    th.Property("last_attributed_touch_data_tilde_technology_partner", th.StringType),
    th.Property("last_attributed_touch_data_tilde_tune_publisher_id", th.IntegerType),
    th.Property("last_attributed_touch_data_tilde_tune_publisher_name", th.StringType),
    th.Property("last_attributed_touch_data_tilde_tune_publisher_sub1", th.StringType),
    th.Property("last_attributed_touch_data_tilde_tune_publisher_sub2", th.StringType),
    th.Property("last_attributed_touch_data_tilde_tune_publisher_sub3", th.StringType),
    th.Property("last_attributed_touch_data_tilde_tune_publisher_sub4", th.StringType),
    th.Property("last_attributed_touch_data_tilde_tune_publisher_sub5", th.StringType),
    th.Property("last_attributed_touch_data_tilde_view_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_view_name", th.StringType),
]

# Additional tilde fields present in all streams EXCEPT IMPRESSION
_TOUCH_TILDE_EXT: list[th.Property] = [
    th.Property("last_attributed_touch_data_tilde_content_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_id", th.IntegerType),
    th.Property("last_attributed_touch_data_tilde_journey_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_journey_name", th.StringType),
    th.Property("last_attributed_touch_data_tilde_organic_search_url", th.StringType),
]

# last_cta_view_data fields — present in attributed streams
_CTA_VIEW: list[th.Property] = [
    th.Property("last_cta_view_data_custom_fields", th.StringType),
    th.Property("last_cta_view_data_dollar_3p", th.StringType),
    th.Property("last_cta_view_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType),
    th.Property("last_cta_view_data_plus_referring_domain", th.StringType),
    th.Property("last_cta_view_data_plus_touch_id", th.StringType),
    th.Property("last_cta_view_data_plus_via_features", th.StringType),
    th.Property("last_cta_view_data_plus_web_format", th.StringType),
    th.Property("last_cta_view_data_tilde_ad_id", th.StringType),
    th.Property("last_cta_view_data_tilde_ad_name", th.StringType),
    th.Property("last_cta_view_data_tilde_ad_set_id", th.StringType),
    th.Property("last_cta_view_data_tilde_ad_set_name", th.StringType),
    th.Property("last_cta_view_data_tilde_advertising_partner_id", th.StringType),
    th.Property("last_cta_view_data_tilde_advertising_partner_name", th.StringType),
    th.Property("last_cta_view_data_tilde_agency", th.StringType),
    th.Property("last_cta_view_data_tilde_agency_id", th.StringType),
    th.Property("last_cta_view_data_tilde_banner_dimensions", th.StringType),
    th.Property("last_cta_view_data_tilde_branch_ad_format", th.StringType),
    th.Property("last_cta_view_data_tilde_campaign", th.StringType),
    th.Property("last_cta_view_data_tilde_campaign_id", th.StringType),
    th.Property("last_cta_view_data_tilde_campaign_type", th.StringType),
    th.Property("last_cta_view_data_tilde_channel", th.StringType),
    th.Property("last_cta_view_data_tilde_creative_id", th.StringType),
    th.Property("last_cta_view_data_tilde_creative_name", th.StringType),
    th.Property("last_cta_view_data_tilde_customer_ad_name", th.StringType),
    th.Property("last_cta_view_data_tilde_customer_ad_set_name", th.StringType),
    th.Property("last_cta_view_data_tilde_customer_campaign", th.StringType),
    th.Property("last_cta_view_data_tilde_customer_keyword", th.StringType),
    th.Property("last_cta_view_data_tilde_customer_placement", th.StringType),
    th.Property("last_cta_view_data_tilde_customer_secondary_publisher", th.StringType),
    th.Property("last_cta_view_data_tilde_customer_sub_site_name", th.StringType),
    th.Property("last_cta_view_data_tilde_external_touch_id", th.StringType),
    th.Property("last_cta_view_data_tilde_feature", th.StringType),
    th.Property("last_cta_view_data_tilde_id", th.IntegerType),
    th.Property("last_cta_view_data_tilde_journey_id", th.StringType),
    th.Property("last_cta_view_data_tilde_journey_name", th.StringType),
    th.Property("last_cta_view_data_tilde_keyword", th.StringType),
    th.Property("last_cta_view_data_tilde_keyword_id", th.StringType),
    th.Property("last_cta_view_data_tilde_optimization_model", th.StringType),
    th.Property("last_cta_view_data_tilde_placement", th.StringType),
    th.Property("last_cta_view_data_tilde_placement_id", th.StringType),
    th.Property("last_cta_view_data_tilde_secondary_ad_format", th.StringType),
    th.Property("last_cta_view_data_tilde_secondary_publisher", th.StringType),
    th.Property("last_cta_view_data_tilde_secondary_publisher_id", th.StringType),
    th.Property("last_cta_view_data_tilde_stage", th.StringType),
    th.Property("last_cta_view_data_tilde_sub_site_name", th.StringType),
    th.Property("last_cta_view_data_tilde_tags", th.StringType),
    th.Property("last_cta_view_data_tilde_technology_partner", th.StringType),
    th.Property("last_cta_view_data_tilde_tune_publisher_id", th.IntegerType),
    th.Property("last_cta_view_data_tilde_tune_publisher_name", th.StringType),
    th.Property("last_cta_view_data_tilde_tune_publisher_sub1", th.StringType),
    th.Property("last_cta_view_data_tilde_tune_publisher_sub2", th.StringType),
    th.Property("last_cta_view_data_tilde_tune_publisher_sub3", th.StringType),
    th.Property("last_cta_view_data_tilde_tune_publisher_sub4", th.StringType),
    th.Property("last_cta_view_data_tilde_tune_publisher_sub5", th.StringType),
    th.Property("last_cta_view_data_tilde_view_id", th.StringType),
    th.Property("last_cta_view_data_tilde_view_name", th.StringType),
    th.Property("last_cta_view_timestamp", th.IntegerType),
    th.Property("last_cta_view_timestamp_iso", th.StringType),
]

# Geographic user_data fields — present in all 7 streams
_GEO: list[th.Property] = [
    th.Property("user_data_geo_city_code", th.IntegerType),
    th.Property("user_data_geo_city_en", th.StringType),
    th.Property("user_data_geo_country_code", th.StringType),
    th.Property("user_data_geo_country_en", th.StringType),
    th.Property("user_data_geo_dma_code", th.IntegerType),
    th.Property("user_data_geo_lat", th.NumberType),
    th.Property("user_data_geo_lon", th.NumberType),
    th.Property("user_data_geo_postal_code", th.StringType),
    th.Property("user_data_geo_region_code", th.StringType),
    th.Property("user_data_geo_region_en", th.StringType),
]

# Cross-platform identity fields — present in all 7 streams
_CROSS_PLATFORM: list[th.Property] = [
    th.Property("user_data_cross_platform_id", th.StringType),
    th.Property("user_data_past_cross_platform_ids", th.StringType),
    th.Property("user_data_prob_cross_platform_ids", th.StringType),
    th.Property("user_data_prob_cross_platform_ids[].id", th.StringType),
    th.Property("user_data_prob_cross_platform_ids[].probability", th.StringType),
]

# Event revenue/commerce fields — present in attributed streams
_EVENT_DATA: list[th.Property] = [
    th.Property("event_data_affiliation", th.StringType),
    th.Property("event_data_coupon", th.StringType),
    th.Property("event_data_currency", th.StringType),
    th.Property("event_data_description", th.StringType),
    th.Property("event_data_exchange_rate", th.NumberType),
    th.Property("event_data_revenue", th.NumberType),
    th.Property("event_data_revenue_in_usd", th.NumberType),
    th.Property("event_data_search_query", th.StringType),
    th.Property("event_data_shipping", th.NumberType),
    th.Property("event_data_tax", th.NumberType),
    th.Property("event_data_transaction_id", th.StringType),
]

# install_activity fields — present in attributed streams
_INSTALL_ACTIVITY: list[th.Property] = [
    th.Property("install_activity_timestamp", th.IntegerType),
    th.Property(
        "install_activity_touch_data_dollar_meta_is_mobile_data_terms_signed",
        th.BooleanType,
    ),
    th.Property("install_activity_touch_data_tilde_campaign", th.StringType),
    th.Property("install_activity_touch_data_tilde_channel", th.StringType),
    th.Property("install_activity_touch_data_tilde_feature", th.StringType),
]

# ---------------------------------------------------------------------------
# Per-stream schema dicts
# ---------------------------------------------------------------------------

EO_CLICK = th.PropertiesList(
    # Core
    th.Property("export_date", th.DateTimeType),
    th.Property("datasource", th.StringType),
    th.Property("id", th.IntegerType),
    th.Property("name", th.StringType),
    th.Property("timestamp", th.IntegerType),
    th.Property("timestamp_iso", th.StringType),
    th.Property("event_timestamp", th.IntegerType),
    th.Property("organization_id", th.IntegerType),
    th.Property("organization_name", th.StringType),
    th.Property("origin", th.StringType),
    th.Property("request_id", th.StringType),
    th.Property("tune_site_id", th.IntegerType),
    th.Property("tune_site_name", th.StringType),
    th.Property("tune_site_event_id", th.IntegerType),
    # Persona
    th.Property("persona_identifiers[].guaranteed", th.StringType),
    th.Property("persona_identifiers[].id", th.StringType),
    th.Property("persona_identifiers[].type", th.StringType),
    # Click-specific
    th.Property("di_match_click_token", th.IntegerType),
    # Attribution state
    th.Property("attributed", th.BooleanType),
    th.Property("custom_data", th.StringType),
    th.Property("customer_event_alias", th.StringType),
    th.Property("deep_linked", th.BooleanType),
    th.Property("first_event_for_user", th.BooleanType),
    th.Property("hash_version", th.StringType),
    th.Property("match_guaranteed", th.BooleanType),
    th.Property("days_from_install_to_opt_in", th.IntegerType),
    th.Property("days_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("hours_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("minutes_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("seconds_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("last_attributed_touch_timestamp", th.IntegerType),
    th.Property("last_attributed_touch_timestamp_iso", th.StringType),
    th.Property("last_attributed_touch_type", th.StringType),
    th.Property("referrer_click_timestamp", th.IntegerType),
    th.Property("store_install_begin_timestamp", th.IntegerType),
    # Touch data — dollar/plus
    th.Property("last_attributed_touch_data_custom_fields", th.StringType),
    th.Property("last_attributed_touch_data_dollar_3p", th.StringType),
    th.Property("last_attributed_touch_data_dollar_marketing_title", th.StringType),
    th.Property(
        "last_attributed_touch_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType
    ),
    th.Property("last_attributed_touch_data_plus_current_feature", th.StringType),
    th.Property("last_attributed_touch_data_plus_referring_domain", th.StringType),
    th.Property("last_attributed_touch_data_plus_touch_id", th.StringType),
    th.Property("last_attributed_touch_data_plus_via_features", th.StringType),
    th.Property("last_attributed_touch_data_plus_web_format", th.StringType),
    # Touch data — tilde
    *_TOUCH_TILDE,
    *_TOUCH_TILDE_EXT,
    th.Property("last_attributed_touch_data_tilde_ad_name", th.StringType),
    th.Property("last_attributed_touch_data_tilde_ad_set_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_ad_set_name", th.StringType),
    th.Property("last_attributed_touch_data_tilde_keyword_match_type", th.StringType),
    # CTA view
    *_CTA_VIEW,
    # Event data
    *_EVENT_DATA,
    # User data
    th.Property("user_data_aaid", th.StringType),
    th.Property("user_data_android_id", th.StringType),
    th.Property("user_data_app_package_name", th.StringType),
    th.Property("user_data_app_version", th.StringType),
    th.Property("user_data_brand", th.StringType),
    th.Property("user_data_browser", th.StringType),
    th.Property("user_data_build", th.StringType),
    th.Property("user_data_cpp_level", th.StringType),
    th.Property("user_data_cpu_type", th.StringType),
    th.Property("user_data_developer_identity", th.StringType),
    th.Property("user_data_device_type", th.StringType),
    th.Property("user_data_environment", th.StringType),
    th.Property("user_data_http_referrer", th.StringType),
    th.Property("user_data_idfa", th.StringType),
    th.Property("user_data_idfv", th.StringType),
    th.Property("user_data_installer_package_name", th.StringType),
    th.Property("user_data_internet_connection_type", th.StringType),
    th.Property("user_data_ip", th.StringType),
    th.Property("user_data_is_jailbroken", th.BooleanType),
    th.Property("user_data_kindle_id", th.StringType),
    th.Property("user_data_language", th.StringType),
    th.Property("user_data_limit_ad_tracking", th.BooleanType),
    th.Property("user_data_model", th.StringType),
    th.Property("user_data_oaid", th.StringType),
    th.Property("user_data_opted_in", th.BooleanType),
    th.Property("user_data_opted_in_status", th.StringType),
    th.Property("user_data_os", th.StringType),
    th.Property("user_data_os_version", th.StringType),
    th.Property("user_data_os_version_android", th.StringType),
    th.Property("user_data_platform", th.StringType),
    th.Property("user_data_referral_source", th.StringType),
    th.Property("user_data_screen_height", th.IntegerType),
    th.Property("user_data_screen_width", th.IntegerType),
    th.Property("user_data_sdk_version", th.StringType),
    th.Property("user_data_tune_mat_id", th.StringType),
    th.Property("user_data_user_agent", th.StringType),
    th.Property("user_data_windows_aid", th.StringType),
    *_GEO,
    *_CROSS_PLATFORM,
).to_dict()

EO_IMPRESSION = th.PropertiesList(
    # Core (no request_id)
    th.Property("export_date", th.DateTimeType),
    th.Property("datasource", th.StringType),
    th.Property("id", th.IntegerType),
    th.Property("name", th.StringType),
    th.Property("timestamp", th.IntegerType),
    th.Property("event_timestamp", th.IntegerType),
    th.Property("organization_id", th.IntegerType),
    th.Property("organization_name", th.StringType),
    th.Property("origin", th.StringType),
    th.Property("tune_site_id", th.IntegerType),
    th.Property("tune_site_name", th.StringType),
    th.Property("tune_site_event_id", th.IntegerType),
    # Persona
    th.Property("persona_identifiers[].guaranteed", th.StringType),
    th.Property("persona_identifiers[].id", th.StringType),
    th.Property("persona_identifiers[].type", th.StringType),
    # Touch data — dollar/plus (subset; no referring_domain or via_features)
    th.Property("last_attributed_touch_data_custom_fields", th.StringType),
    th.Property("last_attributed_touch_data_dollar_3p", th.StringType),
    th.Property("last_attributed_touch_data_dollar_marketing_title", th.StringType),
    th.Property(
        "last_attributed_touch_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType
    ),
    th.Property("last_attributed_touch_data_plus_current_feature", th.StringType),
    th.Property("last_attributed_touch_data_plus_touch_id", th.StringType),
    th.Property("last_attributed_touch_data_plus_web_format", th.StringType),
    # Touch data — tilde (base set only; IMPRESSION is missing ext fields)
    *_TOUCH_TILDE,
    # User data (subset)
    th.Property("user_data_aaid", th.StringType),
    th.Property("user_data_brand", th.StringType),
    th.Property("user_data_browser", th.StringType),
    th.Property("user_data_cpp_level", th.StringType),
    th.Property("user_data_developer_identity", th.StringType),
    th.Property("user_data_device_type", th.StringType),
    th.Property("user_data_environment", th.StringType),
    th.Property("user_data_idfa", th.StringType),
    th.Property("user_data_ip", th.StringType),
    th.Property("user_data_kindle_id", th.StringType),
    th.Property("user_data_language", th.StringType),
    th.Property("user_data_limit_ad_tracking", th.BooleanType),
    th.Property("user_data_model", th.StringType),
    th.Property("user_data_oaid", th.StringType),
    th.Property("user_data_os", th.StringType),
    th.Property("user_data_os_version", th.StringType),
    th.Property("user_data_os_version_android", th.StringType),
    th.Property("user_data_platform", th.StringType),
    th.Property("user_data_tune_mat_id", th.StringType),
    th.Property("user_data_user_agent", th.StringType),
    th.Property("user_data_windows_aid", th.StringType),
    *_GEO,
    *_CROSS_PLATFORM,
).to_dict()

EO_INSTALL = th.PropertiesList(
    # Core
    th.Property("export_date", th.DateTimeType),
    th.Property("datasource", th.StringType),
    th.Property("id", th.IntegerType),
    th.Property("name", th.StringType),
    th.Property("timestamp", th.IntegerType),
    th.Property("timestamp_iso", th.StringType),
    th.Property("event_timestamp", th.IntegerType),
    th.Property("organization_id", th.IntegerType),
    th.Property("organization_name", th.StringType),
    th.Property("origin", th.StringType),
    th.Property("request_id", th.StringType),
    th.Property("tune_site_id", th.IntegerType),
    th.Property("tune_site_name", th.StringType),
    th.Property("tune_site_event_id", th.IntegerType),
    # Persona
    th.Property("persona_identifiers[].guaranteed", th.StringType),
    th.Property("persona_identifiers[].id", th.StringType),
    th.Property("persona_identifiers[].type", th.StringType),
    # Attribution state
    th.Property("attributed", th.BooleanType),
    th.Property("custom_data", th.StringType),
    th.Property("customer_event_alias", th.StringType),
    th.Property("deep_linked", th.BooleanType),
    th.Property("first_event_for_user", th.BooleanType),
    th.Property("hash_version", th.StringType),
    th.Property("match_guaranteed", th.BooleanType),
    th.Property("days_from_install_to_opt_in", th.IntegerType),
    th.Property("days_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("hours_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("minutes_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("seconds_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("last_attributed_touch_timestamp", th.IntegerType),
    th.Property("last_attributed_touch_timestamp_iso", th.StringType),
    th.Property("last_attributed_touch_type", th.StringType),
    th.Property("referrer_click_timestamp", th.IntegerType),
    th.Property("store_install_begin_timestamp", th.IntegerType),
    th.Property(
        "reengagement_activity_touch_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType
    ),
    # Event data
    th.Property("event_data_custom_param_1", th.StringType),
    th.Property("event_data_custom_param_2", th.StringType),
    th.Property("event_data_custom_param_3", th.StringType),
    th.Property("existing_user", th.BooleanType),
    *_EVENT_DATA,
    # Touch data — dollar/plus
    th.Property("last_attributed_touch_data_custom_fields", th.StringType),
    th.Property("last_attributed_touch_data_dollar_3p", th.StringType),
    th.Property("last_attributed_touch_data_dollar_fb_data_terms_not_signed", th.BooleanType),
    th.Property("last_attributed_touch_data_dollar_marketing_title", th.StringType),
    th.Property(
        "last_attributed_touch_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType
    ),
    th.Property("last_attributed_touch_data_plus_current_feature", th.StringType),
    th.Property("last_attributed_touch_data_plus_referring_domain", th.StringType),
    th.Property("last_attributed_touch_data_plus_touch_id", th.StringType),
    th.Property("last_attributed_touch_data_plus_via_features", th.StringType),
    th.Property("last_attributed_touch_data_plus_web_format", th.StringType),
    # Touch data — tilde (full set including ad_set and keyword_match_type)
    *_TOUCH_TILDE,
    *_TOUCH_TILDE_EXT,
    th.Property("last_attributed_touch_data_tilde_ad_name", th.StringType),
    th.Property("last_attributed_touch_data_tilde_ad_set_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_ad_set_name", th.StringType),
    th.Property("last_attributed_touch_data_tilde_keyword_match_type", th.StringType),
    # CTA view
    *_CTA_VIEW,
    # Install activity
    *_INSTALL_ACTIVITY,
    # User data
    th.Property("user_data_aaid", th.StringType),
    th.Property("user_data_android_id", th.StringType),
    th.Property("user_data_app_package_name", th.StringType),
    th.Property("user_data_app_store", th.StringType),
    th.Property("user_data_app_version", th.StringType),
    th.Property("user_data_brand", th.StringType),
    th.Property("user_data_browser", th.StringType),
    th.Property("user_data_build", th.StringType),
    th.Property("user_data_carrier_name", th.StringType),
    th.Property("user_data_cpp_level", th.StringType),
    th.Property("user_data_cpu_type", th.StringType),
    th.Property("user_data_developer_identity", th.StringType),
    th.Property("user_data_device_type", th.StringType),
    th.Property("user_data_environment", th.StringType),
    th.Property("user_data_http_referrer", th.StringType),
    th.Property("user_data_idfa", th.StringType),
    th.Property("user_data_idfv", th.StringType),
    th.Property("user_data_installer_package_name", th.StringType),
    th.Property("user_data_internet_connection_type", th.StringType),
    th.Property("user_data_ip", th.StringType),
    th.Property("user_data_is_jailbroken", th.BooleanType),
    th.Property("user_data_kindle_id", th.StringType),
    th.Property("user_data_language", th.StringType),
    th.Property("user_data_limit_ad_tracking", th.BooleanType),
    th.Property("user_data_model", th.StringType),
    th.Property("user_data_oaid", th.StringType),
    th.Property("user_data_opted_in", th.BooleanType),
    th.Property("user_data_opted_in_status", th.StringType),
    th.Property("user_data_os", th.StringType),
    th.Property("user_data_os_version", th.StringType),
    th.Property("user_data_os_version_android", th.StringType),
    th.Property("user_data_platform", th.StringType),
    th.Property("user_data_referral_source", th.StringType),
    th.Property("user_data_screen_height", th.IntegerType),
    th.Property("user_data_screen_width", th.IntegerType),
    th.Property("user_data_sdk_version", th.StringType),
    th.Property("user_data_tune_mat_id", th.StringType),
    th.Property("user_data_user_agent", th.StringType),
    th.Property("user_data_windows_aid", th.StringType),
    *_GEO,
    *_CROSS_PLATFORM,
).to_dict()

EO_OPEN = th.PropertiesList(
    # Core
    th.Property("export_date", th.DateTimeType),
    th.Property("datasource", th.StringType),
    th.Property("id", th.IntegerType),
    th.Property("name", th.StringType),
    th.Property("timestamp", th.IntegerType),
    th.Property("timestamp_iso", th.StringType),
    th.Property("event_timestamp", th.IntegerType),
    th.Property("organization_id", th.IntegerType),
    th.Property("organization_name", th.StringType),
    th.Property("origin", th.StringType),
    th.Property("request_id", th.StringType),
    th.Property("tune_site_id", th.IntegerType),
    th.Property("tune_site_name", th.StringType),
    th.Property("tune_site_event_id", th.IntegerType),
    # Persona
    th.Property("persona_identifiers[].guaranteed", th.StringType),
    th.Property("persona_identifiers[].id", th.StringType),
    th.Property("persona_identifiers[].type", th.StringType),
    # Attribution state
    th.Property("attributed", th.BooleanType),
    th.Property("custom_data", th.StringType),
    th.Property("customer_event_alias", th.StringType),
    th.Property("deep_linked", th.BooleanType),
    th.Property("first_event_for_user", th.BooleanType),
    th.Property("hash_version", th.StringType),
    th.Property("match_guaranteed", th.BooleanType),
    th.Property("days_from_install_to_opt_in", th.IntegerType),
    th.Property("days_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("hours_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("minutes_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("seconds_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("last_attributed_touch_timestamp", th.IntegerType),
    th.Property("last_attributed_touch_timestamp_iso", th.StringType),
    th.Property("last_attributed_touch_type", th.StringType),
    th.Property("referrer_click_timestamp", th.IntegerType),
    th.Property("store_install_begin_timestamp", th.IntegerType),
    th.Property(
        "reengagement_activity_touch_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType
    ),
    # Event data
    th.Property("event_data_custom_param_1", th.StringType),
    th.Property("event_data_custom_param_2", th.StringType),
    th.Property("event_data_custom_param_3", th.StringType),
    th.Property("existing_user", th.BooleanType),
    *_EVENT_DATA,
    # Touch data — dollar/plus
    th.Property("last_attributed_touch_data_custom_fields", th.StringType),
    th.Property("last_attributed_touch_data_dollar_3p", th.StringType),
    th.Property("last_attributed_touch_data_dollar_fb_data_terms_not_signed", th.BooleanType),
    th.Property("last_attributed_touch_data_dollar_marketing_title", th.StringType),
    th.Property(
        "last_attributed_touch_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType
    ),
    th.Property("last_attributed_touch_data_plus_current_feature", th.StringType),
    th.Property("last_attributed_touch_data_plus_referring_domain", th.StringType),
    th.Property("last_attributed_touch_data_plus_touch_id", th.StringType),
    th.Property("last_attributed_touch_data_plus_via_features", th.StringType),
    th.Property("last_attributed_touch_data_plus_web_format", th.StringType),
    # Touch data — tilde (no ad_set fields for OPEN)
    *_TOUCH_TILDE,
    *_TOUCH_TILDE_EXT,
    th.Property("last_attributed_touch_data_tilde_keyword_match_type", th.StringType),
    # CTA view
    *_CTA_VIEW,
    # Install activity
    *_INSTALL_ACTIVITY,
    # User data
    th.Property("user_data_aaid", th.StringType),
    th.Property("user_data_android_id", th.StringType),
    th.Property("user_data_app_package_name", th.StringType),
    th.Property("user_data_app_store", th.StringType),
    th.Property("user_data_app_version", th.StringType),
    th.Property("user_data_brand", th.StringType),
    th.Property("user_data_browser", th.StringType),
    th.Property("user_data_build", th.StringType),
    th.Property("user_data_carrier_name", th.StringType),
    th.Property("user_data_cpp_level", th.StringType),
    th.Property("user_data_cpu_type", th.StringType),
    th.Property("user_data_developer_identity", th.StringType),
    th.Property("user_data_device_type", th.StringType),
    th.Property("user_data_environment", th.StringType),
    th.Property("user_data_http_referrer", th.StringType),
    th.Property("user_data_idfa", th.StringType),
    th.Property("user_data_idfv", th.StringType),
    th.Property("user_data_installer_package_name", th.StringType),
    th.Property("user_data_internet_connection_type", th.StringType),
    th.Property("user_data_ip", th.StringType),
    th.Property("user_data_is_jailbroken", th.BooleanType),
    th.Property("user_data_kindle_id", th.StringType),
    th.Property("user_data_language", th.StringType),
    th.Property("user_data_limit_ad_tracking", th.BooleanType),
    th.Property("user_data_model", th.StringType),
    th.Property("user_data_oaid", th.StringType),
    th.Property("user_data_opted_in", th.BooleanType),
    th.Property("user_data_opted_in_status", th.StringType),
    th.Property("user_data_os", th.StringType),
    th.Property("user_data_os_version", th.StringType),
    th.Property("user_data_os_version_android", th.StringType),
    th.Property("user_data_platform", th.StringType),
    th.Property("user_data_referral_source", th.StringType),
    th.Property("user_data_screen_height", th.IntegerType),
    th.Property("user_data_screen_width", th.IntegerType),
    th.Property("user_data_sdk_version", th.StringType),
    th.Property("user_data_tune_mat_id", th.StringType),
    th.Property("user_data_user_agent", th.StringType),
    th.Property("user_data_windows_aid", th.StringType),
    *_GEO,
    *_CROSS_PLATFORM,
).to_dict()

EO_REINSTALL = th.PropertiesList(
    # Core
    th.Property("export_date", th.DateTimeType),
    th.Property("datasource", th.StringType),
    th.Property("id", th.IntegerType),
    th.Property("name", th.StringType),
    th.Property("timestamp", th.IntegerType),
    th.Property("timestamp_iso", th.StringType),
    th.Property("event_timestamp", th.IntegerType),
    th.Property("organization_id", th.IntegerType),
    th.Property("organization_name", th.StringType),
    th.Property("origin", th.StringType),
    th.Property("request_id", th.StringType),
    th.Property("tune_site_id", th.IntegerType),
    th.Property("tune_site_name", th.StringType),
    th.Property("tune_site_event_id", th.IntegerType),
    # Persona
    th.Property("persona_identifiers[].guaranteed", th.StringType),
    th.Property("persona_identifiers[].id", th.StringType),
    th.Property("persona_identifiers[].type", th.StringType),
    # Attribution state
    th.Property("attributed", th.BooleanType),
    th.Property("custom_data", th.StringType),
    th.Property("customer_event_alias", th.StringType),
    th.Property("deep_linked", th.BooleanType),
    th.Property("first_event_for_user", th.BooleanType),
    th.Property("hash_version", th.StringType),
    th.Property("match_guaranteed", th.BooleanType),
    th.Property("days_from_install_to_opt_in", th.IntegerType),
    th.Property("days_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("hours_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("minutes_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("seconds_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("last_attributed_touch_timestamp", th.IntegerType),
    th.Property("last_attributed_touch_timestamp_iso", th.StringType),
    th.Property("last_attributed_touch_type", th.StringType),
    th.Property("referrer_click_timestamp", th.IntegerType),
    th.Property("store_install_begin_timestamp", th.IntegerType),
    th.Property(
        "reengagement_activity_touch_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType
    ),
    # Event data
    th.Property("event_data_custom_param_1", th.StringType),
    th.Property("event_data_custom_param_2", th.StringType),
    th.Property("event_data_custom_param_3", th.StringType),
    th.Property("existing_user", th.BooleanType),
    *_EVENT_DATA,
    # Touch data — dollar/plus
    th.Property("last_attributed_touch_data_custom_fields", th.StringType),
    th.Property("last_attributed_touch_data_dollar_3p", th.StringType),
    th.Property("last_attributed_touch_data_dollar_fb_data_terms_not_signed", th.BooleanType),
    th.Property("last_attributed_touch_data_dollar_marketing_title", th.StringType),
    th.Property(
        "last_attributed_touch_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType
    ),
    th.Property("last_attributed_touch_data_plus_current_feature", th.StringType),
    th.Property("last_attributed_touch_data_plus_referring_domain", th.StringType),
    th.Property("last_attributed_touch_data_plus_touch_id", th.StringType),
    th.Property("last_attributed_touch_data_plus_via_features", th.StringType),
    th.Property("last_attributed_touch_data_plus_web_format", th.StringType),
    # Touch data — tilde (includes ad_set fields like INSTALL)
    *_TOUCH_TILDE,
    *_TOUCH_TILDE_EXT,
    th.Property("last_attributed_touch_data_tilde_ad_name", th.StringType),
    th.Property("last_attributed_touch_data_tilde_ad_set_id", th.StringType),
    th.Property("last_attributed_touch_data_tilde_ad_set_name", th.StringType),
    th.Property("last_attributed_touch_data_tilde_keyword_match_type", th.StringType),
    # CTA view
    *_CTA_VIEW,
    # Install activity
    *_INSTALL_ACTIVITY,
    # User data
    th.Property("user_data_aaid", th.StringType),
    th.Property("user_data_android_id", th.StringType),
    th.Property("user_data_app_package_name", th.StringType),
    th.Property("user_data_app_store", th.StringType),
    th.Property("user_data_app_version", th.StringType),
    th.Property("user_data_brand", th.StringType),
    th.Property("user_data_browser", th.StringType),
    th.Property("user_data_build", th.StringType),
    th.Property("user_data_carrier_name", th.StringType),
    th.Property("user_data_cpp_level", th.StringType),
    th.Property("user_data_cpu_type", th.StringType),
    th.Property("user_data_developer_identity", th.StringType),
    th.Property("user_data_device_type", th.StringType),
    th.Property("user_data_environment", th.StringType),
    th.Property("user_data_http_referrer", th.StringType),
    th.Property("user_data_idfa", th.StringType),
    th.Property("user_data_idfv", th.StringType),
    th.Property("user_data_installer_package_name", th.StringType),
    th.Property("user_data_internet_connection_type", th.StringType),
    th.Property("user_data_ip", th.StringType),
    th.Property("user_data_is_jailbroken", th.BooleanType),
    th.Property("user_data_kindle_id", th.StringType),
    th.Property("user_data_language", th.StringType),
    th.Property("user_data_limit_ad_tracking", th.BooleanType),
    th.Property("user_data_model", th.StringType),
    th.Property("user_data_oaid", th.StringType),
    th.Property("user_data_opted_in", th.BooleanType),
    th.Property("user_data_opted_in_status", th.StringType),
    th.Property("user_data_os", th.StringType),
    th.Property("user_data_os_version", th.StringType),
    th.Property("user_data_os_version_android", th.StringType),
    th.Property("user_data_platform", th.StringType),
    th.Property("user_data_referral_source", th.StringType),
    th.Property("user_data_screen_height", th.IntegerType),
    th.Property("user_data_screen_width", th.IntegerType),
    th.Property("user_data_sdk_version", th.StringType),
    th.Property("user_data_tune_mat_id", th.StringType),
    th.Property("user_data_user_agent", th.StringType),
    th.Property("user_data_windows_aid", th.StringType),
    *_GEO,
    *_CROSS_PLATFORM,
).to_dict()

EO_COMMERCE_EVENT = th.PropertiesList(
    # Core
    th.Property("export_date", th.DateTimeType),
    th.Property("datasource", th.StringType),
    th.Property("id", th.IntegerType),
    th.Property("name", th.StringType),
    th.Property("timestamp", th.IntegerType),
    th.Property("event_timestamp", th.IntegerType),
    th.Property("organization_id", th.IntegerType),
    th.Property("organization_name", th.StringType),
    th.Property("origin", th.StringType),
    th.Property("request_id", th.StringType),
    th.Property("tune_site_id", th.IntegerType),
    th.Property("tune_site_name", th.StringType),
    th.Property("tune_site_event_id", th.IntegerType),
    # Persona
    th.Property("persona_identifiers[].guaranteed", th.StringType),
    th.Property("persona_identifiers[].id", th.StringType),
    th.Property("persona_identifiers[].type", th.StringType),
    # Attribution state
    th.Property("attributed", th.BooleanType),
    th.Property("custom_data", th.StringType),
    th.Property("deep_linked", th.BooleanType),
    th.Property("first_event_for_user", th.BooleanType),
    th.Property("match_guaranteed", th.BooleanType),
    th.Property("days_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("last_attributed_touch_timestamp", th.IntegerType),
    th.Property("last_attributed_touch_type", th.StringType),
    th.Property(
        "reengagement_activity_touch_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType
    ),
    # Commerce event data
    th.Property("customer_event_alias", th.StringType),
    th.Property("event_data_ad_type", th.StringType),
    th.Property("event_data_custom_param_1", th.StringType),
    th.Property("event_data_custom_param_2", th.StringType),
    th.Property("event_data_custom_param_3", th.StringType),
    th.Property("existing_user", th.BooleanType),
    *_EVENT_DATA,
    # Content items (array fields serialized as strings in CSV)
    th.Property("content_items[].custom_fields", th.StringType),
    th.Property("content_items[].dollar_address_city", th.StringType),
    th.Property("content_items[].dollar_address_country", th.StringType),
    th.Property("content_items[].dollar_address_postal_code", th.StringType),
    th.Property("content_items[].dollar_address_region", th.StringType),
    th.Property("content_items[].dollar_address_street", th.StringType),
    th.Property("content_items[].dollar_canonical_identifier", th.StringType),
    th.Property("content_items[].dollar_canonical_url", th.StringType),
    th.Property("content_items[].dollar_condition", th.StringType),
    th.Property("content_items[].dollar_content_schema", th.StringType),
    th.Property("content_items[].dollar_creation_timestamp", th.StringType),
    th.Property("content_items[].dollar_currency", th.StringType),
    th.Property("content_items[].dollar_exp_date", th.StringType),
    th.Property("content_items[].dollar_image_captions", th.StringType),
    th.Property("content_items[].dollar_keywords", th.StringType),
    th.Property("content_items[].dollar_latitude", th.StringType),
    th.Property("content_items[].dollar_locally_indexable", th.StringType),
    th.Property("content_items[].dollar_longitude", th.StringType),
    th.Property("content_items[].dollar_og_description", th.StringType),
    th.Property("content_items[].dollar_og_image_url", th.StringType),
    th.Property("content_items[].dollar_og_title", th.StringType),
    th.Property("content_items[].dollar_price", th.StringType),
    th.Property("content_items[].dollar_price_in_usd", th.StringType),
    th.Property("content_items[].dollar_product_brand", th.StringType),
    th.Property("content_items[].dollar_product_category", th.StringType),
    th.Property("content_items[].dollar_product_name", th.StringType),
    th.Property("content_items[].dollar_product_variant", th.StringType),
    th.Property("content_items[].dollar_publicly_indexable", th.StringType),
    th.Property("content_items[].dollar_quantity", th.StringType),
    th.Property("content_items[].dollar_rating", th.StringType),
    th.Property("content_items[].dollar_rating_average", th.StringType),
    th.Property("content_items[].dollar_rating_count", th.StringType),
    th.Property("content_items[].dollar_rating_max", th.StringType),
    th.Property("content_items[].dollar_sku", th.StringType),
    th.Property("content_items[].dollar_value", th.StringType),
    th.Property("content_items[].dollar_value_in_usd", th.StringType),
    # Install activity
    *_INSTALL_ACTIVITY,
    # Touch data — dollar/plus
    th.Property("last_attributed_touch_data_custom_fields", th.StringType),
    th.Property("last_attributed_touch_data_dollar_3p", th.StringType),
    th.Property("last_attributed_touch_data_dollar_fb_data_terms_not_signed", th.BooleanType),
    th.Property("last_attributed_touch_data_dollar_marketing_title", th.StringType),
    th.Property(
        "last_attributed_touch_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType
    ),
    th.Property("last_attributed_touch_data_plus_referring_domain", th.StringType),
    th.Property("last_attributed_touch_data_plus_touch_id", th.StringType),
    th.Property("last_attributed_touch_data_plus_via_features", th.StringType),
    th.Property("last_attributed_touch_data_plus_web_format", th.StringType),
    # Touch data — tilde
    *_TOUCH_TILDE,
    *_TOUCH_TILDE_EXT,
    th.Property("last_attributed_touch_data_tilde_keyword_match_type", th.StringType),
    # CTA view
    *_CTA_VIEW,
    # User data
    th.Property("user_data_aaid", th.StringType),
    th.Property("user_data_android_id", th.StringType),
    th.Property("user_data_app_package_name", th.StringType),
    th.Property("user_data_app_store", th.StringType),
    th.Property("user_data_app_version", th.StringType),
    th.Property("user_data_brand", th.StringType),
    th.Property("user_data_browser", th.StringType),
    th.Property("user_data_build", th.StringType),
    th.Property("user_data_carrier_name", th.StringType),
    th.Property("user_data_cpp_level", th.StringType),
    th.Property("user_data_cpu_type", th.StringType),
    th.Property("user_data_developer_identity", th.StringType),
    th.Property("user_data_device_type", th.StringType),
    th.Property("user_data_environment", th.StringType),
    th.Property("user_data_idfa", th.StringType),
    th.Property("user_data_idfv", th.StringType),
    th.Property("user_data_installer_package_name", th.StringType),
    th.Property("user_data_internet_connection_type", th.StringType),
    th.Property("user_data_ip", th.StringType),
    th.Property("user_data_is_jailbroken", th.BooleanType),
    th.Property("user_data_kindle_id", th.StringType),
    th.Property("user_data_language", th.StringType),
    th.Property("user_data_limit_ad_tracking", th.BooleanType),
    th.Property("user_data_model", th.StringType),
    th.Property("user_data_oaid", th.StringType),
    th.Property("user_data_os", th.StringType),
    th.Property("user_data_os_version", th.StringType),
    th.Property("user_data_os_version_android", th.StringType),
    th.Property("user_data_platform", th.StringType),
    th.Property("user_data_referral_source", th.StringType),
    th.Property("user_data_screen_height", th.IntegerType),
    th.Property("user_data_screen_width", th.IntegerType),
    th.Property("user_data_sdk_version", th.StringType),
    th.Property("user_data_tune_mat_id", th.StringType),
    th.Property("user_data_user_agent", th.StringType),
    th.Property("user_data_windows_aid", th.StringType),
    *_GEO,
    *_CROSS_PLATFORM,
).to_dict()

EO_CUSTOM_EVENT = th.PropertiesList(
    # Core
    th.Property("export_date", th.DateTimeType),
    th.Property("datasource", th.StringType),
    th.Property("id", th.IntegerType),
    th.Property("name", th.StringType),
    th.Property("timestamp", th.IntegerType),
    th.Property("event_timestamp", th.IntegerType),
    th.Property("organization_id", th.IntegerType),
    th.Property("organization_name", th.StringType),
    th.Property("origin", th.StringType),
    th.Property("request_id", th.StringType),
    th.Property("tune_site_id", th.IntegerType),
    th.Property("tune_site_name", th.StringType),
    th.Property("tune_site_event_id", th.IntegerType),
    # Persona
    th.Property("persona_identifiers[].guaranteed", th.StringType),
    th.Property("persona_identifiers[].id", th.StringType),
    th.Property("persona_identifiers[].type", th.StringType),
    # Attribution state
    th.Property("attributed", th.BooleanType),
    th.Property("custom_data", th.StringType),
    th.Property("customer_event_alias", th.StringType),
    th.Property("deep_linked", th.BooleanType),
    th.Property("first_event_for_user", th.BooleanType),
    th.Property("match_guaranteed", th.BooleanType),
    th.Property("days_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("last_attributed_touch_timestamp", th.IntegerType),
    th.Property("last_attributed_touch_type", th.StringType),
    th.Property(
        "reengagement_activity_touch_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType
    ),
    # Event data
    th.Property("event_data_custom_param_1", th.StringType),
    th.Property("event_data_custom_param_2", th.StringType),
    th.Property("event_data_custom_param_3", th.StringType),
    th.Property("event_data_transaction_id", th.StringType),
    th.Property("existing_user", th.BooleanType),
    # Install activity
    *_INSTALL_ACTIVITY,
    # Touch data — dollar/plus
    th.Property("last_attributed_touch_data_custom_fields", th.StringType),
    th.Property("last_attributed_touch_data_dollar_3p", th.StringType),
    th.Property("last_attributed_touch_data_dollar_fb_data_terms_not_signed", th.BooleanType),
    th.Property("last_attributed_touch_data_dollar_marketing_title", th.StringType),
    th.Property(
        "last_attributed_touch_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType
    ),
    th.Property("last_attributed_touch_data_plus_referring_domain", th.StringType),
    th.Property("last_attributed_touch_data_plus_touch_id", th.StringType),
    th.Property("last_attributed_touch_data_plus_via_features", th.StringType),
    th.Property("last_attributed_touch_data_plus_web_format", th.StringType),
    # Touch data — tilde
    *_TOUCH_TILDE,
    *_TOUCH_TILDE_EXT,
    th.Property("last_attributed_touch_data_tilde_keyword_match_type", th.StringType),
    # CTA view
    *_CTA_VIEW,
    # User data
    th.Property("user_data_aaid", th.StringType),
    th.Property("user_data_android_id", th.StringType),
    th.Property("user_data_app_package_name", th.StringType),
    th.Property("user_data_app_store", th.StringType),
    th.Property("user_data_app_version", th.StringType),
    th.Property("user_data_brand", th.StringType),
    th.Property("user_data_browser", th.StringType),
    th.Property("user_data_build", th.StringType),
    th.Property("user_data_carrier_name", th.StringType),
    th.Property("user_data_cpp_level", th.StringType),
    th.Property("user_data_cpu_type", th.StringType),
    th.Property("user_data_developer_identity", th.StringType),
    th.Property("user_data_device_type", th.StringType),
    th.Property("user_data_environment", th.StringType),
    th.Property("user_data_idfa", th.StringType),
    th.Property("user_data_idfv", th.StringType),
    th.Property("user_data_installer_package_name", th.StringType),
    th.Property("user_data_internet_connection_type", th.StringType),
    th.Property("user_data_ip", th.StringType),
    th.Property("user_data_is_jailbroken", th.BooleanType),
    th.Property("user_data_kindle_id", th.StringType),
    th.Property("user_data_language", th.StringType),
    th.Property("user_data_limit_ad_tracking", th.BooleanType),
    th.Property("user_data_model", th.StringType),
    th.Property("user_data_oaid", th.StringType),
    th.Property("user_data_os", th.StringType),
    th.Property("user_data_os_version", th.StringType),
    th.Property("user_data_os_version_android", th.StringType),
    th.Property("user_data_platform", th.StringType),
    th.Property("user_data_referral_source", th.StringType),
    th.Property("user_data_screen_height", th.IntegerType),
    th.Property("user_data_screen_width", th.IntegerType),
    th.Property("user_data_sdk_version", th.StringType),
    th.Property("user_data_tune_mat_id", th.StringType),
    th.Property("user_data_user_agent", th.StringType),
    th.Property("user_data_windows_aid", th.StringType),
    *_GEO,
    *_CROSS_PLATFORM,
).to_dict()

EO_WEB_SESSION_START = th.PropertiesList(
    # Core (no tune_site_event_id)
    th.Property("export_date", th.DateTimeType),
    th.Property("datasource", th.StringType),
    th.Property("id", th.IntegerType),
    th.Property("name", th.StringType),
    th.Property("timestamp", th.IntegerType),
    th.Property("event_timestamp", th.IntegerType),
    th.Property("organization_id", th.IntegerType),
    th.Property("organization_name", th.StringType),
    th.Property("origin", th.StringType),
    th.Property("request_id", th.StringType),
    th.Property("tune_site_id", th.IntegerType),
    th.Property("tune_site_name", th.StringType),
    # Persona
    th.Property("persona_identifiers[].guaranteed", th.StringType),
    th.Property("persona_identifiers[].id", th.StringType),
    th.Property("persona_identifiers[].type", th.StringType),
    # Attribution state
    th.Property("attributed", th.BooleanType),
    th.Property("custom_data", th.StringType),
    th.Property("deep_linked", th.BooleanType),
    th.Property("first_event_for_user", th.BooleanType),
    th.Property("match_guaranteed", th.BooleanType),
    th.Property("days_from_last_attributed_touch_to_event", th.IntegerType),
    th.Property("last_attributed_touch_timestamp", th.IntegerType),
    th.Property("last_attributed_touch_type", th.StringType),
    th.Property(
        "reengagement_activity_touch_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType
    ),
    th.Property("existing_user", th.BooleanType),
    # Install activity
    *_INSTALL_ACTIVITY,
    # Touch data — dollar/plus
    th.Property("last_attributed_touch_data_custom_fields", th.StringType),
    th.Property("last_attributed_touch_data_dollar_3p", th.StringType),
    th.Property("last_attributed_touch_data_dollar_fb_data_terms_not_signed", th.BooleanType),
    th.Property("last_attributed_touch_data_dollar_marketing_title", th.StringType),
    th.Property(
        "last_attributed_touch_data_dollar_meta_is_mobile_data_terms_signed", th.BooleanType
    ),
    th.Property("last_attributed_touch_data_plus_referring_domain", th.StringType),
    th.Property("last_attributed_touch_data_plus_touch_id", th.StringType),
    th.Property("last_attributed_touch_data_plus_via_features", th.StringType),
    th.Property("last_attributed_touch_data_plus_web_format", th.StringType),
    # Touch data — tilde
    *_TOUCH_TILDE,
    *_TOUCH_TILDE_EXT,
    th.Property("last_attributed_touch_data_tilde_keyword_match_type", th.StringType),
    # CTA view
    *_CTA_VIEW,
    # User data (web-only: no mobile identifiers)
    th.Property("user_data_brand", th.StringType),
    th.Property("user_data_browser", th.StringType),
    th.Property("user_data_cpp_level", th.StringType),
    th.Property("user_data_developer_identity", th.StringType),
    th.Property("user_data_device_type", th.StringType),
    th.Property("user_data_environment", th.StringType),
    th.Property("user_data_http_referrer", th.StringType),
    th.Property("user_data_ip", th.StringType),
    th.Property("user_data_is_jailbroken", th.BooleanType),
    th.Property("user_data_language", th.StringType),
    th.Property("user_data_limit_ad_tracking", th.BooleanType),
    th.Property("user_data_model", th.StringType),
    th.Property("user_data_oaid", th.StringType),
    th.Property("user_data_os", th.StringType),
    th.Property("user_data_os_version", th.StringType),
    th.Property("user_data_os_version_android", th.StringType),
    th.Property("user_data_platform", th.StringType),
    th.Property("user_data_sdk_version", th.StringType),
    th.Property("user_data_user_agent", th.StringType),
    *_GEO,
    *_CROSS_PLATFORM,
).to_dict()
